### ISSUE TITLE
Consolidate regular donations notices into civicrm

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/oaf#200]
Currently we have regular donations in paypal and in stripe, but it's not clear if the payments are getting posted to civicrm. Regular donations aren't coming up in civicrm (people have made an initial recurring donation but then the following ones don't turn up), but I can't see the bank account, paypal account or stripe account to see if they are actually being processed.

We should fix/consolidate all this so it comes up nicely in civicrm and it's clear who's paying what/when, which will help us more quickly be able to respond to fix payments and know if people are dropping off etc.

**Comment by kat** [comment]
@equivalentideas you should have received an invitation to join the OAF stripe team - please check your email

**Comment by equivalentideas** [comment]
got it thanks

**Comment by henare** [comment]
>Currently we have regular donations in paypal...

We currently have 7 [recurring donations in PayPal](https://www.paypal.com/au/cgi-bin/webscr?cmd=_merchant-hub). As of January 2015 these don't show up in CiviCRM because we switched our payment processor to Stripe.

There's a bit of manual work involved if we want to consolidate these onto Stripe. I'm taking this ticket to be about that work.

>and in stripe, but it's not clear if the payments are getting posted to civicrm. Regular donations aren't coming up in civicrm...

The ones from Stripe should be. This is a bug:  #205.

**Comment by jamezpolley** [comment]
We don't use paypal, or civicrm any more.
