### ISSUE TITLE
People are making recurring donations when they don't mean to

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#237]
We've had several emails from people that have mistakenly signed up to recurring donations - that's not good.

**Comment by equivalentideas** [comment]
There's a bit of discussion on this in this issue https://github.com/openaustralia/oaf/issues/235#issuecomment-223848610

**Comment by henare** [comment]
@equivalentideas was the fix implemented on #235 done before or after the other people that have reported this issue, i.e. can we close this because we think it's fixed?

**Comment by equivalentideas** [comment]
After most of them. We've had a couple since, but _much_ lower rate for the number of people coming through the page.

I'm happy to close this and reopen if we think necessary as we send more emails. I think to some extent it's a cost of defaulting to recurring and it's very quick to fix for the people who miss it.

**Comment by henare** [comment]
>I'm happy to close this and reopen if we think necessary as we send more emails.

Closed until we confirm this is a problem as we send more emails.

>I think to some extent it's a cost of defaulting to recurring and it's very quick to fix for the people who miss it.

It's an alarming thing to happen (evident from the tone of some of the emails) and it's a design problem we wouldn't accept elsewhere and shouldn't accept here either.
