### ISSUE TITLE
Cash out Bitcoin donations

### ISSUE THREAD

**Issue by henare** [openaustralia/oaf#246]
For quite a while we've had a bitcoin address for donations that @mlandauer set up ages ago. In May this year someone donated bitcoins valued at over AUD$2000. We should cash this out.

**Comment by henare** [comment]
Assigning to @kat to investigate because she was the person that supplied the bitcoin address to the donor.

**Comment by kat** [comment]
Reassigning to @mlandauer as the owner of the Bitcoin wallet to cash this out

**Comment by kat** [comment]
@mlandauer we had another donation - it'd be great if you could transfer out to the OAF account. Thanks!

**Comment by henare** [comment]
[We now have](https://blockchain.info/address/1B3566EMs5nXjRJkFPn4KF95Gz2XnMhLav) about [AUD$3,900](http://www.xe.com/currencyconverter/convert/?Amount=4.13732804&From=XBT&To=AUD) in this wallet. We don't want to lose them and they should be in our charity's bank account. So we need to [sell them](https://bitcoin.com.au/order?sell). It should only take a few minutes. Can you please spare the time @mlandauer?

**Comment by kat** [comment]
@mlandauer Was this done?

**Comment by mlandauer** [comment]
Balance of bitcoin wallet transferred to account controlled by @kat.

**Comment by jamezpolley** [comment]
@kat do you have any update on this?

**Comment by katska** [comment]
@jamezpolley This issue was drawn out a couple of times because of getting access to the account back, and I simply forgot about the github issue in the meantime. reflecting on this issue since, I realise I don't understand the impetus to move them from where they are to a bank account. I believe its been a good strategy so far to leave them where they are. Closing the ticket for now. Feel free to reopen or open another internal issue if there's something I'm missing.
