### ISSUE TITLE
What's the signup/opt-out process for TVFY and RTK?

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/oaf#277]
During #273, this question has come up:

> - Thanks for including the links where emails were gathered! Your sign up forms for Open Australia look great but I did notice the forms for Right to Know (https://www.righttoknow.org.au/profile/sign_in?r=%2F) and They Vote for You (https://theyvoteforyou.org.au/users/sign_up) do not allow someone to explicitly opt in to receiving emailed newsletters. Can you tell us how someone would opt into an email list from those pages? Is there an opt in checkbox/subscribe form later on in the process?

I'm not sure of the answer to this offhand, so I'm making a ticket to track the fact that I need to get an answer.

**Comment by jamezpolley** [comment]
RightToKnow - I can't find anything that would tell someone that their email address is going to be used for emails from the OAF. The only mention I can see is on the sign-in form:

> We will not reveal your email address to anybody unless you or the law tell us to.

So to answer the questions:

> Can you tell us how someone would opt into an email list from those pages? 

I can't see anything

> Is there an opt in checkbox/subscribe form later on in the process?

I can't see anything.

**Comment by jamezpolley** [comment]
TheyVoteForYou: Signup for does state "Add new policies, edit and improve division summaries, and subscribe to updates about the policies that matter to you.", but nothing about any other emails.

So, same answers here.

**Comment by mlandauer** [comment]
I'm not aware that we have anything explicitly about emailing people from OAF very occasionally for TheyVoteForYou and RightToKnow. I think this is something we should definitely add when we get a chance. Because we do it so rarely and it's very clear why we're doing it (help support the projects), I feel like we're not abusing any trust here. However, of course it would be better to have this written down explicitly so we should do that.

In terms of opting out of OpenAustralia Foundation emails (that aren't the transactional project emails) we always include an unsubscribe link on mail outs and that link should unsubscribe from all OAF email (that isn't transactional project stuff). For each transactional project email there should also be a link to update preferences or unsubscribe.
