### ISSUE TITLE
Replace akismet with wordfence on oaf.org.au

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/oaf#325]
We currently have no effective spam comment protection which is pain. We've had [Wordfence](https://www.wordfence.com/) recommended to us as a good free service. Akismet is now not free ($7/month) for our use case because we accept donations on the site.

**Comment by katska** [comment]
I'm told captcha and wordfence have free tiers. Catpcha 3 doesn't require an input from the user and has secret smarts. Whereas wordfence gives more visibility and lets you adjust the parameters.

**Comment by kat** [comment]
If you read their T&C, even being a nonprofit puts us in their paid tier! boo! only "personal and noncommercial" is free. 

—
Kat Szuminska

--- original message ---
On July 2, 2020, 11:10 AM GMT+10 notifications@github.com wrote:



I'm told captcha and wordfence have free tiers. Catpcha 3 doesn't require an input from the user and has secret smarts. Whereas wordfence gives more visibility and lets you adjust the parameters.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by mlandauer** [comment]
Hmm.. We're already using Wordfence and it looks like scanning of comments is switched on. So I guess this is already done. I've just gone through the 20 something spam comments in the queue and checked through them one by one.

So, I guess I can close this issue then
