### ISSUE TITLE
Move all donors from stripe to donorbox

### ISSUE THREAD

**Issue by katska** [openaustralia/oaf#332]
. We currently have about 48 subscriptions left over going directly on stripe which users can't manage themselves. Those subscriptions are earning us about $200/month. I think we should cancel them all and email them asking to sign up again on the new system. We risk a bunch of people not signing up again but there's also a possibility that some people might donate more. Also, it will simplify managing things for us and will allow those users to manage things themselves.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3q5dx)

**Comment by katska** [comment]
Looks like there's a migration path for this https://donorbox.zendesk.com/hc/en-us/articles/360020294132-How-to-migrate-existing-Stripe-recurring-donations-on-another-platform-to-Donorbox

My proposed plan is 
1- write to the users telling them we're migrating their monthly donation.  
Thank them for their ongoing support
Remind them we appreciate their ongoing support and specify example of value they bring
Let them know they have direct control to amend their details or cancel their support

2- Migrate them - https://donorbox.zendesk.com/hc/en-us/articles/360020294132-How-to-migrate-existing-Stripe-recurring-donations-on-another-platform-to-Donorbox
(and respond to any questions/cancellations)

@mlandauer are you happy for us to go this route? I'll do as much as I can myself and ask for your help where needed.

**Comment by katska** [comment]
@mlandauer I've assigned to you to review this plan and make any suggestions if you agree.

**Comment by mlandauer** [comment]
@katska good find! This is so much better than just cancelling and asking people to setup recurring donations again.

The only bit of your plan I question is when we write to the people. I suggest we do it after we've migrated them because then that way we can immediately tell them they can have direct control over their donations immediately.

**Comment by kat** [comment]
Cool! The only concern I have is that they ask us to send them the subscriber details -What's your view on us emailing this information to them? We're not sharing payment info but sill feels not ideal.

—
Katherine Szuminska

--- original message ---
On July 1, 2021, 12:43 PM GMT+10 ***@***.*** wrote:



@katska good find! This is so much better than just cancelling and asking people to setup recurring donations again.

The only bit of your plan I question is when we write to the people. I suggest we do it after we've migrated them because then that way we can immediately tell them they can have direct control over their donations immediately.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by katska** [comment]
These are the currently active stripe subscriptions https://dashboard.stripe.com/subscriptions

Exporting:

* Customer ID (Stripe's customer ID)
* First and last name(s)
* Email address(es)
* Currency
* Donation amount
* Due date
* Frequency (monthly, yearly, etc)

**Comment by katska** [comment]
https://app.frontapp.com/open/cnv_8l3db45

**Comment by katska** [comment]
Seems like they can initiate from their end. The help information was missing this crucial bit. I'm now waiting for them to get back to me. The initial response was quick :) so I'm hopeful we can wrap this in the next day or two

**Comment by mlandauer** [comment]
@katska how close to done is this now?

**Comment by mlandauer** [comment]
Closing this issue in favour of the duplicate #334
